# Generated by Django 5.2 on 2025-08-19 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackquestion',
            options={'ordering': ['ordre']},
        ),
        migrations.AddField(
            model_name='binome',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='allow_multiple_responses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'RH'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
